use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// API input (matches SDK TelemetryEvent)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize)]
pub struct TelemetryEventInput {
    /// Generated by the server when not provided (spec section 5.2).
    pub id: Option<Uuid>,
    #[serde(rename = "type")]
    pub event_type: String,
    pub timestamp: DateTime<Utc>,
    pub session_id: Option<Uuid>,
    pub ctx_token: Option<String>,
    pub turn_id: Option<String>,
    pub source_role: Option<String>,
    pub content_telemetry_id: Option<Uuid>,
    pub content_url: Option<String>,
    pub content_id: Option<String>,
    /// Output-artifact identity (spec 5.2): required on content_reproduced,
    /// content_cited and content_presented events.
    pub output_id: Option<String>,
    pub output_element_id: Option<String>,
    /// On content_presented or content_reproduced, the id of the associated
    /// content_cited event; absent for uncited presentations and uncredited
    /// reproductions.
    pub citation_id: Option<Uuid>,
    /// On content_engaged, the id of the exact content_presented event the
    /// action occurred on. Required (spec 6.8).
    pub presentation_id: Option<Uuid>,
    pub license_ref: Option<String>,
    pub product_id: Option<Uuid>,
    pub turn: Option<serde_json::Value>,
    #[serde(default)]
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Deserialize)]
pub struct EventsCreateRequest {
    /// Spec envelope discriminator. When present it must be "event"
    /// (standalone) or "event_batch" — session documents go to
    /// /sessions/bulk.
    pub document_type: Option<String>,
    /// Exact-minor version rule applies when present (spec 5.7.4).
    pub schema_version: Option<String>,
    pub session_id: Option<String>,
    /// Immediate parent session that delegated work to this session
    /// (spec 5.1). Applies to every event in the batch.
    pub parent_session_id: Option<Uuid>,
    pub ctx_token: Option<String>,
    /// Session-level fields a standalone envelope mirrors at Grounding
    /// conformance and above (spec 7.1). Used to reconstruct the session
    /// when events arrive for a session the server has not seen.
    pub agent_id: Option<String>,
    pub started_at: Option<DateTime<Utc>>,
    /// Spec standalone event envelope: a single event under `event`.
    pub event: Option<TelemetryEventInput>,
    /// Spec event batch envelope: multiple events per request (spec 7.1).
    #[serde(default)]
    pub events: Vec<TelemetryEventInput>,
}

// ---------------------------------------------------------------------------
// Edge/origin API input (sessionless publisher emitter events)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize)]
pub struct EdgeEventInput {
    pub id: Option<Uuid>,
    #[serde(rename = "type")]
    pub event_type: String,
    pub timestamp: DateTime<Utc>,
    pub source_role: Option<String>,
    pub content_telemetry_id: Option<Uuid>,
    pub content_url: Option<String>,
    pub content_id: Option<String>,
    pub license_ref: Option<String>,
    #[serde(default)]
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Deserialize)]
pub struct EdgeEventsCreateRequest {
    pub events: Vec<EdgeEventInput>,
}

// ---------------------------------------------------------------------------
// Database row
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct EventRow {
    pub id: Uuid,
    pub session_id: Option<Uuid>,
    pub organization_id: Uuid,
    pub event_type: String,
    pub source_role: Option<String>,
    pub content_telemetry_id: Option<Uuid>,
    pub content_url: Option<String>,
    pub content_id: Option<String>,
    pub turn_id: Option<String>,
    pub output_id: Option<String>,
    pub output_element_id: Option<String>,
    pub citation_id: Option<Uuid>,
    pub presentation_id: Option<Uuid>,
    pub license_ref: Option<String>,
    pub product_id: Option<Uuid>,
    pub turn_data: Option<serde_json::Value>,
    pub event_data: serde_json::Value,
    pub event_timestamp: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// API responses
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize)]
pub struct EventsCreatedResponse {
    pub status: String,
    pub events_created: usize,
}
